export const HEADERCLICK = "header/HEADERCLICK";
export const HEADERCLOSE = "header/HEADERCLOSE";
export const HANDLEHOMETWEETSLIST = "home/HANDLEHEADERTWEETSLIST";
export const HANDLE_ONMOUSEENTER = "home/HANDLE_ONMOUSEENTER";
export const HANDLE_ONMOUSELEAVE = "home/HANDLE_ONMOUSELEAVE";
export const HANDLE_TREND_LIST = "home/HANDLE_TREND_LIST";
export const HANDLE_MORE_TREND_LIST = "home/HANDLE_MORE_TREND_LIST";









