export const HEADERCLICK = "header/HEADERCLICK";
export const HEADERCLOSE = "header/HEADERCLOSE";
export const HANDLEHOMETWEETSLIST = "home/HANDLEHEADERTWEETSLIST";
export const HANDLE_ONMOUSEENTER = "home/HANDLE_ONMOUSEENTER";
export const HANDLE_ONMOUSELEAVE = "home/HANDLE_ONMOUSELEAVE";






